"""add indexes to execution_model

Revision ID: 3834c837f5f2
Revises: bb0c5e8d05e2
Create Date: 2019-11-26 08:42:13.575198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3834c837f5f2'
down_revision = 'bb0c5e8d05e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('execution_model__index_on_execution_id_model_name', 'execution_model', ['execution_id', 'model_name'], unique=True, schema='rdl')
    op.create_index('execution_model__index_on_model_name_completed_on', 'execution_model', ['model_name', 'completed_on'], unique=False, schema='rdl')
    op.create_index(op.f('ix_rdl_execution_model_completed_on'), 'execution_model', ['completed_on'], unique=False, schema='rdl')
    op.create_index(op.f('ix_rdl_execution_model_status'), 'execution_model', ['status'], unique=False, schema='rdl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rdl_execution_model_status'), table_name='execution_model', schema='rdl')
    op.drop_index(op.f('ix_rdl_execution_model_completed_on'), table_name='execution_model', schema='rdl')
    op.drop_index('execution_model__index_on_model_name_completed_on', table_name='execution_model', schema='rdl')
    op.drop_index('execution_model__index_on_execution_id_model_name', table_name='execution_model', schema='rdl')
    # ### end Alembic commands ###
